<div class="wrap page_settings">
    <h2 style="margin-bottom: 30px;">Favoriten API</h2>
    <?php settings_errors('xlib-api-favorites-' . $activeTab) ?>
    <h2 class="nav-tab-wrapper">
        <a
            href="?page=xlib-api-favorites&tab=settings"
            class="nav-tab <?php echo ($activeTab == 'settings') ? 'nav-tab-active' : '' ?>"
        >
            Allgemeine Einstellung
        </a>
    </h2>
    <form method="post" action="options.php">
        <?php settings_fields('xlib-api-favorites-' . $activeTab); ?>
        <?php do_settings_sections('xlib-api-favorites-' . $activeTab) ?>
        <?php submit_button(); ?>
    </form>
</div>