<div class="wrap vaf-admin-page">
    <hr class="wp-header-end">

    <?php settings_errors() ?>

    <div class="postbox vaf-postbox admin-headline">
        <div class="inside">
            <h1><?php echo $this->title ?></h1>
        </div>
    </div>

    <form name="form" action="" method="post">
        <?php wp_nonce_field($this->nonce) ?>
        <input type="hidden" name="action" value="update" />

        <?php if (!empty($this->description)) : ?>
            <p><?php echo $this->description ?></p>
        <?php endif; ?>

        <?php foreach ($this->fieldGroups as $fieldGroup) : ?>
            <?php if ($fieldGroup['isTable']) : ?>
                <table class="form-table" role="presentation">
                    <tbody>
                    <?php foreach ($fieldGroup['fields'] as $field) : ?>
                        <?php echo $field ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else : ?>
                <?php echo $fieldGroup['content'] ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php submit_button(); ?>
    </form>
</div>